"""adiciona time tracking em issues

Revision ID: 7dacb75f4e4d
Revises: b71d46295ef3
Create Date: 2026-07-18 19:23:20.177079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dacb75f4e4d'
down_revision: Union[str, Sequence[str], None] = 'b71d46295ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('original_estimate_seconds', sa.Integer(), nullable=True))
    op.add_column('issues', sa.Column('time_spent_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'time_spent_seconds')
    op.drop_column('issues', 'original_estimate_seconds')
    # ### end Alembic commands ###
