"""schema inicial

Revision ID: 8e3632b6fc7e
Revises: 
Create Date: 2026-07-18 08:07:52.704195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e3632b6fc7e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('jira_cloud_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_key'), 'sites', ['key'], unique=True)
    op.create_table('person_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('jira_account_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'jira_account_id', name='uq_identity_site_account')
    )
    op.create_index(op.f('ix_person_identities_person_id'), 'person_identities', ['person_id'], unique=False)
    op.create_index(op.f('ix_person_identities_site_id'), 'person_identities', ['site_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('jira_project_id', sa.String(length=64), nullable=False),
    sa.Column('jira_key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'jira_project_id', name='uq_project_site_jira_id')
    )
    op.create_index(op.f('ix_projects_jira_key'), 'projects', ['jira_key'], unique=False)
    op.create_index(op.f('ix_projects_site_id'), 'projects', ['site_id'], unique=False)
    op.create_table('sync_cursors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_page_token', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'entity_type', name='uq_cursor_site_entity')
    )
    op.create_index(op.f('ix_sync_cursors_site_id'), 'sync_cursors', ['site_id'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_site_id'), 'sync_runs', ['site_id'], unique=False)
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('jira_board_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'jira_board_id', name='uq_board_project_jira_id')
    )
    op.create_index(op.f('ix_boards_project_id'), 'boards', ['project_id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('jira_issue_id', sa.String(length=64), nullable=False),
    sa.Column('jira_key', sa.String(length=32), nullable=False),
    sa.Column('issue_type', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=128), nullable=False),
    sa.Column('status_category', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=64), nullable=True),
    sa.Column('assignee_person_id', sa.Integer(), nullable=True),
    sa.Column('reporter_person_id', sa.Integer(), nullable=True),
    sa.Column('story_points', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reporter_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'jira_issue_id', name='uq_issue_site_jira_id')
    )
    op.create_index(op.f('ix_issues_assignee_person_id'), 'issues', ['assignee_person_id'], unique=False)
    op.create_index(op.f('ix_issues_jira_key'), 'issues', ['jira_key'], unique=False)
    op.create_index(op.f('ix_issues_project_id'), 'issues', ['project_id'], unique=False)
    op.create_index(op.f('ix_issues_reporter_person_id'), 'issues', ['reporter_person_id'], unique=False)
    op.create_index(op.f('ix_issues_site_id'), 'issues', ['site_id'], unique=False)
    op.create_index('ix_issues_updated_at', 'issues', ['updated_at'], unique=False)
    op.create_table('issue_field_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('jira_changelog_entry_id', sa.String(length=64), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('from_value', sa.String(length=1000), nullable=True),
    sa.Column('to_value', sa.String(length=1000), nullable=True),
    sa.Column('from_status_category', sa.String(length=32), nullable=True),
    sa.Column('to_status_category', sa.String(length=32), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by_person_id', sa.Integer(), nullable=True),
    sa.Column('sync_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jira_changelog_entry_id')
    )
    op.create_index('ix_issue_field_changes_changed_at_field', 'issue_field_changes', ['changed_at', 'field_name'], unique=False)
    op.create_index(op.f('ix_issue_field_changes_field_name'), 'issue_field_changes', ['field_name'], unique=False)
    op.create_index(op.f('ix_issue_field_changes_issue_id'), 'issue_field_changes', ['issue_id'], unique=False)
    op.create_table('sprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('jira_sprint_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('complete_date', sa.DateTime(), nullable=True),
    sa.Column('goal', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'jira_sprint_id', name='uq_sprint_board_jira_id')
    )
    op.create_index(op.f('ix_sprints_board_id'), 'sprints', ['board_id'], unique=False)
    op.create_table('issue_sprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id', 'sprint_id', name='uq_issue_sprint')
    )
    op.create_index(op.f('ix_issue_sprints_issue_id'), 'issue_sprints', ['issue_id'], unique=False)
    op.create_index('ix_issue_sprints_sprint_id', 'issue_sprints', ['sprint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_issue_sprints_sprint_id', table_name='issue_sprints')
    op.drop_index(op.f('ix_issue_sprints_issue_id'), table_name='issue_sprints')
    op.drop_table('issue_sprints')
    op.drop_index(op.f('ix_sprints_board_id'), table_name='sprints')
    op.drop_table('sprints')
    op.drop_index(op.f('ix_issue_field_changes_issue_id'), table_name='issue_field_changes')
    op.drop_index(op.f('ix_issue_field_changes_field_name'), table_name='issue_field_changes')
    op.drop_index('ix_issue_field_changes_changed_at_field', table_name='issue_field_changes')
    op.drop_table('issue_field_changes')
    op.drop_index('ix_issues_updated_at', table_name='issues')
    op.drop_index(op.f('ix_issues_site_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_reporter_person_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_project_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_jira_key'), table_name='issues')
    op.drop_index(op.f('ix_issues_assignee_person_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_boards_project_id'), table_name='boards')
    op.drop_table('boards')
    op.drop_index(op.f('ix_sync_runs_site_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_sync_cursors_site_id'), table_name='sync_cursors')
    op.drop_table('sync_cursors')
    op.drop_index(op.f('ix_projects_site_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_jira_key'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_person_identities_site_id'), table_name='person_identities')
    op.drop_index(op.f('ix_person_identities_person_id'), table_name='person_identities')
    op.drop_table('person_identities')
    op.drop_index(op.f('ix_sites_key'), table_name='sites')
    op.drop_table('sites')
    op.drop_table('people')
    # ### end Alembic commands ###
