"""adiciona issue_links

Revision ID: 98aa33c46478
Revises: 7dacb75f4e4d
Create Date: 2026-07-18 21:48:55.494167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98aa33c46478'
down_revision: Union[str, Sequence[str], None] = '7dacb75f4e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('jira_link_id', sa.String(length=64), nullable=False),
    sa.Column('link_type_name', sa.String(length=128), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('linked_jira_key', sa.String(length=32), nullable=False),
    sa.Column('linked_summary', sa.String(length=2000), nullable=False),
    sa.Column('linked_status', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id', 'jira_link_id', name='uq_issue_link_jira_id')
    )
    op.create_index('ix_issue_links_issue_id', 'issue_links', ['issue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_issue_links_issue_id', table_name='issue_links')
    op.drop_table('issue_links')
    # ### end Alembic commands ###
