"""adiciona parent_jira_key em issues

Revision ID: a73941366c4f
Revises: 98aa33c46478
Create Date: 2026-07-20 20:31:10.470367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a73941366c4f'
down_revision: Union[str, Sequence[str], None] = '98aa33c46478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('parent_jira_key', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'parent_jira_key')
    # ### end Alembic commands ###
