"""adiciona tech_map_entries

Revision ID: f9e2f2f3b547
Revises: a73941366c4f
Create Date: 2026-07-20 20:32:47.599661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9e2f2f3b547'
down_revision: Union[str, Sequence[str], None] = 'a73941366c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tech_map_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=255), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('frente', sa.String(length=255), nullable=True),
    sa.Column('tarefa', sa.Text(), nullable=False),
    sa.Column('atuantes', sa.String(length=255), nullable=True),
    sa.Column('ice_impacto', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('ice_confianca', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('ice_facilidade', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('ice_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('entrega', sa.String(length=64), nullable=True),
    sa.Column('tamanho_projeto', sa.String(length=64), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('lancamento', sa.String(length=64), nullable=True),
    sa.Column('epic_jira_key', sa.String(length=32), nullable=True),
    sa.Column('raw_row', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tech_map_entries_epic_jira_key'), 'tech_map_entries', ['epic_jira_key'], unique=False)
    op.create_index(op.f('ix_tech_map_entries_sheet_name'), 'tech_map_entries', ['sheet_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tech_map_entries_sheet_name'), table_name='tech_map_entries')
    op.drop_index(op.f('ix_tech_map_entries_epic_jira_key'), table_name='tech_map_entries')
    op.drop_table('tech_map_entries')
    # ### end Alembic commands ###
